// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_runfast.proto

#ifndef PROTOBUF_msg_5frunfast_2eproto__INCLUDED
#define PROTOBUF_msg_5frunfast_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "public_pro.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_5frunfast_2eproto();
void protobuf_AssignDesc_msg_5frunfast_2eproto();
void protobuf_ShutdownFile_msg_5frunfast_2eproto();

class MsgRunFastPlayer;
class MsgRunFastCardInfo;
class MsgRunFastActon;
class MsgRunFastUserOutCard;
class MsgRunFastMSGRoomParam;
class MsgRunFastRoom;
class MsgRunFastGameOverInfo;
class MsgRunFastRoomShowDown;
class MsgRunFastIntegralCount;

enum TRunFastPlayerWik {
  ASK_RF_NULL = 1,
  ASK_TISHI = 2,
  ASK_BUCHU = 4,
  ASK_CHUPAI = 8
};
bool TRunFastPlayerWik_IsValid(int value);
const TRunFastPlayerWik TRunFastPlayerWik_MIN = ASK_RF_NULL;
const TRunFastPlayerWik TRunFastPlayerWik_MAX = ASK_CHUPAI;
const int TRunFastPlayerWik_ARRAYSIZE = TRunFastPlayerWik_MAX + 1;

const ::google::protobuf::EnumDescriptor* TRunFastPlayerWik_descriptor();
inline const ::std::string& TRunFastPlayerWik_Name(TRunFastPlayerWik value) {
  return ::google::protobuf::internal::NameOfEnum(
    TRunFastPlayerWik_descriptor(), value);
}
inline bool TRunFastPlayerWik_Parse(
    const ::std::string& name, TRunFastPlayerWik* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TRunFastPlayerWik>(
    TRunFastPlayerWik_descriptor(), name, value);
}
enum TRunFastPlayerState {
  STATE_RF_READY = 1,
  STATE_BAODAN = 2,
  STATE_GUOPAI = 4,
  STATE_BAOPEI = 8,
  STATE_GUANMEN = 16,
  STATE_RF_NEWROLE = 32,
  STATE_RF_ROOM_OWNER = 64,
  STATE_RF_RELIEVE = 128,
  STATE_RF_LEAVE = 256,
  STATE_RF_LIMIT = 512,
  STATE_RF_OFFLINE = 1024,
  STATE_RF_TRUST = 2048,
  STATE_RF_TRUSTMAX = 4096,
  STATE_RF_CONTINUEGAME = 8192
};
bool TRunFastPlayerState_IsValid(int value);
const TRunFastPlayerState TRunFastPlayerState_MIN = STATE_RF_READY;
const TRunFastPlayerState TRunFastPlayerState_MAX = STATE_RF_CONTINUEGAME;
const int TRunFastPlayerState_ARRAYSIZE = TRunFastPlayerState_MAX + 1;

const ::google::protobuf::EnumDescriptor* TRunFastPlayerState_descriptor();
inline const ::std::string& TRunFastPlayerState_Name(TRunFastPlayerState value) {
  return ::google::protobuf::internal::NameOfEnum(
    TRunFastPlayerState_descriptor(), value);
}
inline bool TRunFastPlayerState_Parse(
    const ::std::string& name, TRunFastPlayerState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TRunFastPlayerState>(
    TRunFastPlayerState_descriptor(), name, value);
}
enum TRunFastState {
  TRunFastStateWait = 0,
  TRunFastStateCheckStartGame = 1,
  TRunFastStateStartGame = 2,
  TRunFastStateSendCard = 3,
  TRunFastStateAction = 4,
  TRunFastStateOutCard = 5,
  TRunFastStateShowDown = 6,
  TRunFastStateRelieveRoom = 7
};
bool TRunFastState_IsValid(int value);
const TRunFastState TRunFastState_MIN = TRunFastStateWait;
const TRunFastState TRunFastState_MAX = TRunFastStateRelieveRoom;
const int TRunFastState_ARRAYSIZE = TRunFastState_MAX + 1;

const ::google::protobuf::EnumDescriptor* TRunFastState_descriptor();
inline const ::std::string& TRunFastState_Name(TRunFastState value) {
  return ::google::protobuf::internal::NameOfEnum(
    TRunFastState_descriptor(), value);
}
inline bool TRunFastState_Parse(
    const ::std::string& name, TRunFastState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TRunFastState>(
    TRunFastState_descriptor(), name, value);
}
enum TRunFastCT {
  CT_RF_ERROR = 0,
  CT_RF_SINGLE = 1,
  CT_RF_DOUBLE = 2,
  CT_RF_THREE_TIAO = 3,
  CT_RF_THREE_TIAO_WITH_ONE = 4,
  CT_RF_THREE_TIAO_WITH_DOUBLE = 5,
  CT_RF_SHUN_ZI = 6,
  CT_RF_LIAN_DUI = 7,
  CT_RF_FEIJI = 8,
  CT_RF_ZHADAN_RUAN = 9,
  CT_RF_ZHADAN_YING = 10,
  CT_RF_ZHADAN_LAIZI = 11,
  CT_RF_FOUR_KING = 12,
  CT_RF_TONG_HUA_SHU = 13
};
bool TRunFastCT_IsValid(int value);
const TRunFastCT TRunFastCT_MIN = CT_RF_ERROR;
const TRunFastCT TRunFastCT_MAX = CT_RF_TONG_HUA_SHU;
const int TRunFastCT_ARRAYSIZE = TRunFastCT_MAX + 1;

const ::google::protobuf::EnumDescriptor* TRunFastCT_descriptor();
inline const ::std::string& TRunFastCT_Name(TRunFastCT value) {
  return ::google::protobuf::internal::NameOfEnum(
    TRunFastCT_descriptor(), value);
}
inline bool TRunFastCT_Parse(
    const ::std::string& name, TRunFastCT* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TRunFastCT>(
    TRunFastCT_descriptor(), name, value);
}
// ===================================================================

class MsgRunFastPlayer : public ::google::protobuf::Message {
 public:
  MsgRunFastPlayer();
  virtual ~MsgRunFastPlayer();

  MsgRunFastPlayer(const MsgRunFastPlayer& from);

  inline MsgRunFastPlayer& operator=(const MsgRunFastPlayer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastPlayer& default_instance();

  void Swap(MsgRunFastPlayer* other);

  // implements Message ----------------------------------------------

  MsgRunFastPlayer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastPlayer& from);
  void MergeFrom(const MsgRunFastPlayer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .MsgPlayerInfo player_base = 1;
  inline bool has_player_base() const;
  inline void clear_player_base();
  static const int kPlayerBaseFieldNumber = 1;
  inline const ::MsgPlayerInfo& player_base() const;
  inline ::MsgPlayerInfo* mutable_player_base();
  inline ::MsgPlayerInfo* release_player_base();
  inline void set_allocated_player_base(::MsgPlayerInfo* player_base);

  // optional uint32 state = 2;
  inline bool has_state() const;
  inline void clear_state();
  static const int kStateFieldNumber = 2;
  inline ::google::protobuf::uint32 state() const;
  inline void set_state(::google::protobuf::uint32 value);

  // optional uint32 hand_count = 3;
  inline bool has_hand_count() const;
  inline void clear_hand_count();
  static const int kHandCountFieldNumber = 3;
  inline ::google::protobuf::uint32 hand_count() const;
  inline void set_hand_count(::google::protobuf::uint32 value);

  // repeated .MsgRunFastCardInfo card_list = 4;
  inline int card_list_size() const;
  inline void clear_card_list();
  static const int kCardListFieldNumber = 4;
  inline const ::MsgRunFastCardInfo& card_list(int index) const;
  inline ::MsgRunFastCardInfo* mutable_card_list(int index);
  inline ::MsgRunFastCardInfo* add_card_list();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >&
      card_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >*
      mutable_card_list();

  // optional uint32 seats = 5;
  inline bool has_seats() const;
  inline void clear_seats();
  static const int kSeatsFieldNumber = 5;
  inline ::google::protobuf::uint32 seats() const;
  inline void set_seats(::google::protobuf::uint32 value);

  // optional uint32 zhadan_count = 6;
  inline bool has_zhadan_count() const;
  inline void clear_zhadan_count();
  static const int kZhadanCountFieldNumber = 6;
  inline ::google::protobuf::uint32 zhadan_count() const;
  inline void set_zhadan_count(::google::protobuf::uint32 value);

  // optional int64 score = 7;
  inline bool has_score() const;
  inline void clear_score();
  static const int kScoreFieldNumber = 7;
  inline ::google::protobuf::int64 score() const;
  inline void set_score(::google::protobuf::int64 value);

  // optional int64 show_down_score = 8;
  inline bool has_show_down_score() const;
  inline void clear_show_down_score();
  static const int kShowDownScoreFieldNumber = 8;
  inline ::google::protobuf::int64 show_down_score() const;
  inline void set_show_down_score(::google::protobuf::int64 value);

  // optional uint32 integral_num = 9;
  inline bool has_integral_num() const;
  inline void clear_integral_num();
  static const int kIntegralNumFieldNumber = 9;
  inline ::google::protobuf::uint32 integral_num() const;
  inline void set_integral_num(::google::protobuf::uint32 value);

  // repeated .MsgRunFastCardInfo out_card = 10;
  inline int out_card_size() const;
  inline void clear_out_card();
  static const int kOutCardFieldNumber = 10;
  inline const ::MsgRunFastCardInfo& out_card(int index) const;
  inline ::MsgRunFastCardInfo* mutable_out_card(int index);
  inline ::MsgRunFastCardInfo* add_out_card();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >&
      out_card() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >*
      mutable_out_card();

  // optional uint32 out_type = 11;
  inline bool has_out_type() const;
  inline void clear_out_type();
  static const int kOutTypeFieldNumber = 11;
  inline ::google::protobuf::uint32 out_type() const;
  inline void set_out_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgRunFastPlayer)
 private:
  inline void set_has_player_base();
  inline void clear_has_player_base();
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_hand_count();
  inline void clear_has_hand_count();
  inline void set_has_seats();
  inline void clear_has_seats();
  inline void set_has_zhadan_count();
  inline void clear_has_zhadan_count();
  inline void set_has_score();
  inline void clear_has_score();
  inline void set_has_show_down_score();
  inline void clear_has_show_down_score();
  inline void set_has_integral_num();
  inline void clear_has_integral_num();
  inline void set_has_out_type();
  inline void clear_has_out_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::MsgPlayerInfo* player_base_;
  ::google::protobuf::uint32 state_;
  ::google::protobuf::uint32 hand_count_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo > card_list_;
  ::google::protobuf::uint32 seats_;
  ::google::protobuf::uint32 zhadan_count_;
  ::google::protobuf::int64 score_;
  ::google::protobuf::int64 show_down_score_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo > out_card_;
  ::google::protobuf::uint32 integral_num_;
  ::google::protobuf::uint32 out_type_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastPlayer* default_instance_;
};
// -------------------------------------------------------------------

class MsgRunFastCardInfo : public ::google::protobuf::Message {
 public:
  MsgRunFastCardInfo();
  virtual ~MsgRunFastCardInfo();

  MsgRunFastCardInfo(const MsgRunFastCardInfo& from);

  inline MsgRunFastCardInfo& operator=(const MsgRunFastCardInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastCardInfo& default_instance();

  void Swap(MsgRunFastCardInfo* other);

  // implements Message ----------------------------------------------

  MsgRunFastCardInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastCardInfo& from);
  void MergeFrom(const MsgRunFastCardInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 card = 1;
  inline bool has_card() const;
  inline void clear_card();
  static const int kCardFieldNumber = 1;
  inline ::google::protobuf::uint32 card() const;
  inline void set_card(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgRunFastCardInfo)
 private:
  inline void set_has_card();
  inline void clear_has_card();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 card_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastCardInfo* default_instance_;
};
// -------------------------------------------------------------------

class MsgRunFastActon : public ::google::protobuf::Message {
 public:
  MsgRunFastActon();
  virtual ~MsgRunFastActon();

  MsgRunFastActon(const MsgRunFastActon& from);

  inline MsgRunFastActon& operator=(const MsgRunFastActon& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastActon& default_instance();

  void Swap(MsgRunFastActon* other);

  // implements Message ----------------------------------------------

  MsgRunFastActon* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastActon& from);
  void MergeFrom(const MsgRunFastActon& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 new_actionid = 1;
  inline bool has_new_actionid() const;
  inline void clear_new_actionid();
  static const int kNewActionidFieldNumber = 1;
  inline ::google::protobuf::uint64 new_actionid() const;
  inline void set_new_actionid(::google::protobuf::uint64 value);

  // optional uint64 old_actionid = 2;
  inline bool has_old_actionid() const;
  inline void clear_old_actionid();
  static const int kOldActionidFieldNumber = 2;
  inline ::google::protobuf::uint64 old_actionid() const;
  inline void set_old_actionid(::google::protobuf::uint64 value);

  // repeated .MsgRunFastCardInfo last_out_card = 3;
  inline int last_out_card_size() const;
  inline void clear_last_out_card();
  static const int kLastOutCardFieldNumber = 3;
  inline const ::MsgRunFastCardInfo& last_out_card(int index) const;
  inline ::MsgRunFastCardInfo* mutable_last_out_card(int index);
  inline ::MsgRunFastCardInfo* add_last_out_card();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >&
      last_out_card() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >*
      mutable_last_out_card();

  // optional uint32 last_out_type = 4;
  inline bool has_last_out_type() const;
  inline void clear_last_out_type();
  static const int kLastOutTypeFieldNumber = 4;
  inline ::google::protobuf::uint32 last_out_type() const;
  inline void set_last_out_type(::google::protobuf::uint32 value);

  // optional uint32 wik = 5;
  inline bool has_wik() const;
  inline void clear_wik();
  static const int kWikFieldNumber = 5;
  inline ::google::protobuf::uint32 wik() const;
  inline void set_wik(::google::protobuf::uint32 value);

  // repeated .MsgRunFastPlayer player_list = 6;
  inline int player_list_size() const;
  inline void clear_player_list();
  static const int kPlayerListFieldNumber = 6;
  inline const ::MsgRunFastPlayer& player_list(int index) const;
  inline ::MsgRunFastPlayer* mutable_player_list(int index);
  inline ::MsgRunFastPlayer* add_player_list();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >&
      player_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >*
      mutable_player_list();

  // @@protoc_insertion_point(class_scope:MsgRunFastActon)
 private:
  inline void set_has_new_actionid();
  inline void clear_has_new_actionid();
  inline void set_has_old_actionid();
  inline void clear_has_old_actionid();
  inline void set_has_last_out_type();
  inline void clear_has_last_out_type();
  inline void set_has_wik();
  inline void clear_has_wik();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 new_actionid_;
  ::google::protobuf::uint64 old_actionid_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo > last_out_card_;
  ::google::protobuf::uint32 last_out_type_;
  ::google::protobuf::uint32 wik_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer > player_list_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastActon* default_instance_;
};
// -------------------------------------------------------------------

class MsgRunFastUserOutCard : public ::google::protobuf::Message {
 public:
  MsgRunFastUserOutCard();
  virtual ~MsgRunFastUserOutCard();

  MsgRunFastUserOutCard(const MsgRunFastUserOutCard& from);

  inline MsgRunFastUserOutCard& operator=(const MsgRunFastUserOutCard& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastUserOutCard& default_instance();

  void Swap(MsgRunFastUserOutCard* other);

  // implements Message ----------------------------------------------

  MsgRunFastUserOutCard* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastUserOutCard& from);
  void MergeFrom(const MsgRunFastUserOutCard& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 old_actionid = 1;
  inline bool has_old_actionid() const;
  inline void clear_old_actionid();
  static const int kOldActionidFieldNumber = 1;
  inline ::google::protobuf::uint64 old_actionid() const;
  inline void set_old_actionid(::google::protobuf::uint64 value);

  // optional uint32 out_type = 2;
  inline bool has_out_type() const;
  inline void clear_out_type();
  static const int kOutTypeFieldNumber = 2;
  inline ::google::protobuf::uint32 out_type() const;
  inline void set_out_type(::google::protobuf::uint32 value);

  // optional uint32 hand_count = 3;
  inline bool has_hand_count() const;
  inline void clear_hand_count();
  static const int kHandCountFieldNumber = 3;
  inline ::google::protobuf::uint32 hand_count() const;
  inline void set_hand_count(::google::protobuf::uint32 value);

  // repeated uint32 outcard_laiziLogic = 4;
  inline int outcard_laizilogic_size() const;
  inline void clear_outcard_laizilogic();
  static const int kOutcardLaiziLogicFieldNumber = 4;
  inline ::google::protobuf::uint32 outcard_laizilogic(int index) const;
  inline void set_outcard_laizilogic(int index, ::google::protobuf::uint32 value);
  inline void add_outcard_laizilogic(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      outcard_laizilogic() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_outcard_laizilogic();

  // repeated .MsgRunFastCardInfo out_card = 5;
  inline int out_card_size() const;
  inline void clear_out_card();
  static const int kOutCardFieldNumber = 5;
  inline const ::MsgRunFastCardInfo& out_card(int index) const;
  inline ::MsgRunFastCardInfo* mutable_out_card(int index);
  inline ::MsgRunFastCardInfo* add_out_card();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >&
      out_card() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >*
      mutable_out_card();

  // optional bool is_baodan = 6;
  inline bool has_is_baodan() const;
  inline void clear_is_baodan();
  static const int kIsBaodanFieldNumber = 6;
  inline bool is_baodan() const;
  inline void set_is_baodan(bool value);

  // @@protoc_insertion_point(class_scope:MsgRunFastUserOutCard)
 private:
  inline void set_has_old_actionid();
  inline void clear_has_old_actionid();
  inline void set_has_out_type();
  inline void clear_has_out_type();
  inline void set_has_hand_count();
  inline void clear_has_hand_count();
  inline void set_has_is_baodan();
  inline void clear_has_is_baodan();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 old_actionid_;
  ::google::protobuf::uint32 out_type_;
  ::google::protobuf::uint32 hand_count_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > outcard_laizilogic_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo > out_card_;
  bool is_baodan_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastUserOutCard* default_instance_;
};
// -------------------------------------------------------------------

class MsgRunFastMSGRoomParam : public ::google::protobuf::Message {
 public:
  MsgRunFastMSGRoomParam();
  virtual ~MsgRunFastMSGRoomParam();

  MsgRunFastMSGRoomParam(const MsgRunFastMSGRoomParam& from);

  inline MsgRunFastMSGRoomParam& operator=(const MsgRunFastMSGRoomParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastMSGRoomParam& default_instance();

  void Swap(MsgRunFastMSGRoomParam* other);

  // implements Message ----------------------------------------------

  MsgRunFastMSGRoomParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastMSGRoomParam& from);
  void MergeFrom(const MsgRunFastMSGRoomParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 room_run_time = 1;
  inline bool has_room_run_time() const;
  inline void clear_room_run_time();
  static const int kRoomRunTimeFieldNumber = 1;
  inline ::google::protobuf::uint32 room_run_time() const;
  inline void set_room_run_time(::google::protobuf::uint32 value);

  // optional uint32 room_param = 2;
  inline bool has_room_param() const;
  inline void clear_room_param();
  static const int kRoomParamFieldNumber = 2;
  inline ::google::protobuf::uint32 room_param() const;
  inline void set_room_param(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgRunFastMSGRoomParam)
 private:
  inline void set_has_room_run_time();
  inline void clear_has_room_run_time();
  inline void set_has_room_param();
  inline void clear_has_room_param();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 room_run_time_;
  ::google::protobuf::uint32 room_param_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastMSGRoomParam* default_instance_;
};
// -------------------------------------------------------------------

class MsgRunFastRoom : public ::google::protobuf::Message {
 public:
  MsgRunFastRoom();
  virtual ~MsgRunFastRoom();

  MsgRunFastRoom(const MsgRunFastRoom& from);

  inline MsgRunFastRoom& operator=(const MsgRunFastRoom& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastRoom& default_instance();

  void Swap(MsgRunFastRoom* other);

  // implements Message ----------------------------------------------

  MsgRunFastRoom* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastRoom& from);
  void MergeFrom(const MsgRunFastRoom& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .TRunFastState room_state = 1;
  inline bool has_room_state() const;
  inline void clear_room_state();
  static const int kRoomStateFieldNumber = 1;
  inline ::TRunFastState room_state() const;
  inline void set_room_state(::TRunFastState value);

  // optional uint32 state_time = 2;
  inline bool has_state_time() const;
  inline void clear_state_time();
  static const int kStateTimeFieldNumber = 2;
  inline ::google::protobuf::uint32 state_time() const;
  inline void set_state_time(::google::protobuf::uint32 value);

  // repeated .MsgRunFastPlayer player_list = 3;
  inline int player_list_size() const;
  inline void clear_player_list();
  static const int kPlayerListFieldNumber = 3;
  inline const ::MsgRunFastPlayer& player_list(int index) const;
  inline ::MsgRunFastPlayer* mutable_player_list(int index);
  inline ::MsgRunFastPlayer* add_player_list();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >&
      player_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >*
      mutable_player_list();

  // optional uint64 action_id = 4;
  inline bool has_action_id() const;
  inline void clear_action_id();
  static const int kActionIdFieldNumber = 4;
  inline ::google::protobuf::uint64 action_id() const;
  inline void set_action_id(::google::protobuf::uint64 value);

  // optional uint64 room_id = 5;
  inline bool has_room_id() const;
  inline void clear_room_id();
  static const int kRoomIdFieldNumber = 5;
  inline ::google::protobuf::uint64 room_id() const;
  inline void set_room_id(::google::protobuf::uint64 value);

  // optional uint32 game_count = 6;
  inline bool has_game_count() const;
  inline void clear_game_count();
  static const int kGameCountFieldNumber = 6;
  inline ::google::protobuf::uint32 game_count() const;
  inline void set_game_count(::google::protobuf::uint32 value);

  // optional .MsgCreatePrivateRoom private_room = 7;
  inline bool has_private_room() const;
  inline void clear_private_room();
  static const int kPrivateRoomFieldNumber = 7;
  inline const ::MsgCreatePrivateRoom& private_room() const;
  inline ::MsgCreatePrivateRoom* mutable_private_room();
  inline ::MsgCreatePrivateRoom* release_private_room();
  inline void set_allocated_private_room(::MsgCreatePrivateRoom* private_room);

  // optional .MsgRunFastUserOutCard last_outcard = 8;
  inline bool has_last_outcard() const;
  inline void clear_last_outcard();
  static const int kLastOutcardFieldNumber = 8;
  inline const ::MsgRunFastUserOutCard& last_outcard() const;
  inline ::MsgRunFastUserOutCard* mutable_last_outcard();
  inline ::MsgRunFastUserOutCard* release_last_outcard();
  inline void set_allocated_last_outcard(::MsgRunFastUserOutCard* last_outcard);

  // optional uint32 wik = 10;
  inline bool has_wik() const;
  inline void clear_wik();
  static const int kWikFieldNumber = 10;
  inline ::google::protobuf::uint32 wik() const;
  inline void set_wik(::google::protobuf::uint32 value);

  // optional uint32 room_pay_type = 11;
  inline bool has_room_pay_type() const;
  inline void clear_room_pay_type();
  static const int kRoomPayTypeFieldNumber = 11;
  inline ::google::protobuf::uint32 room_pay_type() const;
  inline void set_room_pay_type(::google::protobuf::uint32 value);

  // optional .MsgRunFastMSGRoomParam msg_room_param = 12;
  inline bool has_msg_room_param() const;
  inline void clear_msg_room_param();
  static const int kMsgRoomParamFieldNumber = 12;
  inline const ::MsgRunFastMSGRoomParam& msg_room_param() const;
  inline ::MsgRunFastMSGRoomParam* mutable_msg_room_param();
  inline ::MsgRunFastMSGRoomParam* release_msg_room_param();
  inline void set_allocated_msg_room_param(::MsgRunFastMSGRoomParam* msg_room_param);

  // @@protoc_insertion_point(class_scope:MsgRunFastRoom)
 private:
  inline void set_has_room_state();
  inline void clear_has_room_state();
  inline void set_has_state_time();
  inline void clear_has_state_time();
  inline void set_has_action_id();
  inline void clear_has_action_id();
  inline void set_has_room_id();
  inline void clear_has_room_id();
  inline void set_has_game_count();
  inline void clear_has_game_count();
  inline void set_has_private_room();
  inline void clear_has_private_room();
  inline void set_has_last_outcard();
  inline void clear_has_last_outcard();
  inline void set_has_wik();
  inline void clear_has_wik();
  inline void set_has_room_pay_type();
  inline void clear_has_room_pay_type();
  inline void set_has_msg_room_param();
  inline void clear_has_msg_room_param();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int room_state_;
  ::google::protobuf::uint32 state_time_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer > player_list_;
  ::google::protobuf::uint64 action_id_;
  ::google::protobuf::uint64 room_id_;
  ::MsgCreatePrivateRoom* private_room_;
  ::google::protobuf::uint32 game_count_;
  ::google::protobuf::uint32 wik_;
  ::MsgRunFastUserOutCard* last_outcard_;
  ::MsgRunFastMSGRoomParam* msg_room_param_;
  ::google::protobuf::uint32 room_pay_type_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastRoom* default_instance_;
};
// -------------------------------------------------------------------

class MsgRunFastGameOverInfo : public ::google::protobuf::Message {
 public:
  MsgRunFastGameOverInfo();
  virtual ~MsgRunFastGameOverInfo();

  MsgRunFastGameOverInfo(const MsgRunFastGameOverInfo& from);

  inline MsgRunFastGameOverInfo& operator=(const MsgRunFastGameOverInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastGameOverInfo& default_instance();

  void Swap(MsgRunFastGameOverInfo* other);

  // implements Message ----------------------------------------------

  MsgRunFastGameOverInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastGameOverInfo& from);
  void MergeFrom(const MsgRunFastGameOverInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 role_id = 1;
  inline bool has_role_id() const;
  inline void clear_role_id();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::uint64 role_id() const;
  inline void set_role_id(::google::protobuf::uint64 value);

  // optional int64 max_score = 2;
  inline bool has_max_score() const;
  inline void clear_max_score();
  static const int kMaxScoreFieldNumber = 2;
  inline ::google::protobuf::int64 max_score() const;
  inline void set_max_score(::google::protobuf::int64 value);

  // optional uint32 zhadan_count = 3;
  inline bool has_zhadan_count() const;
  inline void clear_zhadan_count();
  static const int kZhadanCountFieldNumber = 3;
  inline ::google::protobuf::uint32 zhadan_count() const;
  inline void set_zhadan_count(::google::protobuf::uint32 value);

  // optional uint32 win_count = 4;
  inline bool has_win_count() const;
  inline void clear_win_count();
  static const int kWinCountFieldNumber = 4;
  inline ::google::protobuf::uint32 win_count() const;
  inline void set_win_count(::google::protobuf::uint32 value);

  // optional uint32 lose_count = 5;
  inline bool has_lose_count() const;
  inline void clear_lose_count();
  static const int kLoseCountFieldNumber = 5;
  inline ::google::protobuf::uint32 lose_count() const;
  inline void set_lose_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgRunFastGameOverInfo)
 private:
  inline void set_has_role_id();
  inline void clear_has_role_id();
  inline void set_has_max_score();
  inline void clear_has_max_score();
  inline void set_has_zhadan_count();
  inline void clear_has_zhadan_count();
  inline void set_has_win_count();
  inline void clear_has_win_count();
  inline void set_has_lose_count();
  inline void clear_has_lose_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 role_id_;
  ::google::protobuf::int64 max_score_;
  ::google::protobuf::uint32 zhadan_count_;
  ::google::protobuf::uint32 win_count_;
  ::google::protobuf::uint32 lose_count_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastGameOverInfo* default_instance_;
};
// -------------------------------------------------------------------

class MsgRunFastRoomShowDown : public ::google::protobuf::Message {
 public:
  MsgRunFastRoomShowDown();
  virtual ~MsgRunFastRoomShowDown();

  MsgRunFastRoomShowDown(const MsgRunFastRoomShowDown& from);

  inline MsgRunFastRoomShowDown& operator=(const MsgRunFastRoomShowDown& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastRoomShowDown& default_instance();

  void Swap(MsgRunFastRoomShowDown* other);

  // implements Message ----------------------------------------------

  MsgRunFastRoomShowDown* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastRoomShowDown& from);
  void MergeFrom(const MsgRunFastRoomShowDown& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .TRunFastState room_state = 1;
  inline bool has_room_state() const;
  inline void clear_room_state();
  static const int kRoomStateFieldNumber = 1;
  inline ::TRunFastState room_state() const;
  inline void set_room_state(::TRunFastState value);

  // optional uint32 state_time = 2;
  inline bool has_state_time() const;
  inline void clear_state_time();
  static const int kStateTimeFieldNumber = 2;
  inline ::google::protobuf::uint32 state_time() const;
  inline void set_state_time(::google::protobuf::uint32 value);

  // repeated .MsgRunFastPlayer player_list = 3;
  inline int player_list_size() const;
  inline void clear_player_list();
  static const int kPlayerListFieldNumber = 3;
  inline const ::MsgRunFastPlayer& player_list(int index) const;
  inline ::MsgRunFastPlayer* mutable_player_list(int index);
  inline ::MsgRunFastPlayer* add_player_list();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >&
      player_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >*
      mutable_player_list();

  // optional uint64 room_id = 4;
  inline bool has_room_id() const;
  inline void clear_room_id();
  static const int kRoomIdFieldNumber = 4;
  inline ::google::protobuf::uint64 room_id() const;
  inline void set_room_id(::google::protobuf::uint64 value);

  // optional uint32 game_count = 5;
  inline bool has_game_count() const;
  inline void clear_game_count();
  static const int kGameCountFieldNumber = 5;
  inline ::google::protobuf::uint32 game_count() const;
  inline void set_game_count(::google::protobuf::uint32 value);

  // optional uint32 time = 6;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 6;
  inline ::google::protobuf::uint32 time() const;
  inline void set_time(::google::protobuf::uint32 value);

  // repeated .MsgRunFastGameOverInfo over_info = 7;
  inline int over_info_size() const;
  inline void clear_over_info();
  static const int kOverInfoFieldNumber = 7;
  inline const ::MsgRunFastGameOverInfo& over_info(int index) const;
  inline ::MsgRunFastGameOverInfo* mutable_over_info(int index);
  inline ::MsgRunFastGameOverInfo* add_over_info();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastGameOverInfo >&
      over_info() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastGameOverInfo >*
      mutable_over_info();

  // repeated .MsgRunFastIntegralCount integral_list = 8;
  inline int integral_list_size() const;
  inline void clear_integral_list();
  static const int kIntegralListFieldNumber = 8;
  inline const ::MsgRunFastIntegralCount& integral_list(int index) const;
  inline ::MsgRunFastIntegralCount* mutable_integral_list(int index);
  inline ::MsgRunFastIntegralCount* add_integral_list();
  inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastIntegralCount >&
      integral_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastIntegralCount >*
      mutable_integral_list();

  // @@protoc_insertion_point(class_scope:MsgRunFastRoomShowDown)
 private:
  inline void set_has_room_state();
  inline void clear_has_room_state();
  inline void set_has_state_time();
  inline void clear_has_state_time();
  inline void set_has_room_id();
  inline void clear_has_room_id();
  inline void set_has_game_count();
  inline void clear_has_game_count();
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int room_state_;
  ::google::protobuf::uint32 state_time_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer > player_list_;
  ::google::protobuf::uint64 room_id_;
  ::google::protobuf::uint32 game_count_;
  ::google::protobuf::uint32 time_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastGameOverInfo > over_info_;
  ::google::protobuf::RepeatedPtrField< ::MsgRunFastIntegralCount > integral_list_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastRoomShowDown* default_instance_;
};
// -------------------------------------------------------------------

class MsgRunFastIntegralCount : public ::google::protobuf::Message {
 public:
  MsgRunFastIntegralCount();
  virtual ~MsgRunFastIntegralCount();

  MsgRunFastIntegralCount(const MsgRunFastIntegralCount& from);

  inline MsgRunFastIntegralCount& operator=(const MsgRunFastIntegralCount& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MsgRunFastIntegralCount& default_instance();

  void Swap(MsgRunFastIntegralCount* other);

  // implements Message ----------------------------------------------

  MsgRunFastIntegralCount* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MsgRunFastIntegralCount& from);
  void MergeFrom(const MsgRunFastIntegralCount& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 roleid = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleidFieldNumber = 1;
  inline ::google::protobuf::uint64 roleid() const;
  inline void set_roleid(::google::protobuf::uint64 value);

  // optional uint32 count = 2;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 2;
  inline ::google::protobuf::uint32 count() const;
  inline void set_count(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MsgRunFastIntegralCount)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_count();
  inline void clear_has_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::uint32 count_;
  friend void  protobuf_AddDesc_msg_5frunfast_2eproto();
  friend void protobuf_AssignDesc_msg_5frunfast_2eproto();
  friend void protobuf_ShutdownFile_msg_5frunfast_2eproto();

  void InitAsDefaultInstance();
  static MsgRunFastIntegralCount* default_instance_;
};
// ===================================================================


// ===================================================================

// MsgRunFastPlayer

// optional .MsgPlayerInfo player_base = 1;
inline bool MsgRunFastPlayer::has_player_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastPlayer::set_has_player_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastPlayer::clear_has_player_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastPlayer::clear_player_base() {
  if (player_base_ != NULL) player_base_->::MsgPlayerInfo::Clear();
  clear_has_player_base();
}
inline const ::MsgPlayerInfo& MsgRunFastPlayer::player_base() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.player_base)
  return player_base_ != NULL ? *player_base_ : *default_instance_->player_base_;
}
inline ::MsgPlayerInfo* MsgRunFastPlayer::mutable_player_base() {
  set_has_player_base();
  if (player_base_ == NULL) player_base_ = new ::MsgPlayerInfo;
  // @@protoc_insertion_point(field_mutable:MsgRunFastPlayer.player_base)
  return player_base_;
}
inline ::MsgPlayerInfo* MsgRunFastPlayer::release_player_base() {
  clear_has_player_base();
  ::MsgPlayerInfo* temp = player_base_;
  player_base_ = NULL;
  return temp;
}
inline void MsgRunFastPlayer::set_allocated_player_base(::MsgPlayerInfo* player_base) {
  delete player_base_;
  player_base_ = player_base;
  if (player_base) {
    set_has_player_base();
  } else {
    clear_has_player_base();
  }
  // @@protoc_insertion_point(field_set_allocated:MsgRunFastPlayer.player_base)
}

// optional uint32 state = 2;
inline bool MsgRunFastPlayer::has_state() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRunFastPlayer::set_has_state() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRunFastPlayer::clear_has_state() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRunFastPlayer::clear_state() {
  state_ = 0u;
  clear_has_state();
}
inline ::google::protobuf::uint32 MsgRunFastPlayer::state() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.state)
  return state_;
}
inline void MsgRunFastPlayer::set_state(::google::protobuf::uint32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastPlayer.state)
}

// optional uint32 hand_count = 3;
inline bool MsgRunFastPlayer::has_hand_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgRunFastPlayer::set_has_hand_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgRunFastPlayer::clear_has_hand_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgRunFastPlayer::clear_hand_count() {
  hand_count_ = 0u;
  clear_has_hand_count();
}
inline ::google::protobuf::uint32 MsgRunFastPlayer::hand_count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.hand_count)
  return hand_count_;
}
inline void MsgRunFastPlayer::set_hand_count(::google::protobuf::uint32 value) {
  set_has_hand_count();
  hand_count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastPlayer.hand_count)
}

// repeated .MsgRunFastCardInfo card_list = 4;
inline int MsgRunFastPlayer::card_list_size() const {
  return card_list_.size();
}
inline void MsgRunFastPlayer::clear_card_list() {
  card_list_.Clear();
}
inline const ::MsgRunFastCardInfo& MsgRunFastPlayer::card_list(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.card_list)
  return card_list_.Get(index);
}
inline ::MsgRunFastCardInfo* MsgRunFastPlayer::mutable_card_list(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastPlayer.card_list)
  return card_list_.Mutable(index);
}
inline ::MsgRunFastCardInfo* MsgRunFastPlayer::add_card_list() {
  // @@protoc_insertion_point(field_add:MsgRunFastPlayer.card_list)
  return card_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >&
MsgRunFastPlayer::card_list() const {
  // @@protoc_insertion_point(field_list:MsgRunFastPlayer.card_list)
  return card_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >*
MsgRunFastPlayer::mutable_card_list() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastPlayer.card_list)
  return &card_list_;
}

// optional uint32 seats = 5;
inline bool MsgRunFastPlayer::has_seats() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgRunFastPlayer::set_has_seats() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgRunFastPlayer::clear_has_seats() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgRunFastPlayer::clear_seats() {
  seats_ = 0u;
  clear_has_seats();
}
inline ::google::protobuf::uint32 MsgRunFastPlayer::seats() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.seats)
  return seats_;
}
inline void MsgRunFastPlayer::set_seats(::google::protobuf::uint32 value) {
  set_has_seats();
  seats_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastPlayer.seats)
}

// optional uint32 zhadan_count = 6;
inline bool MsgRunFastPlayer::has_zhadan_count() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgRunFastPlayer::set_has_zhadan_count() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgRunFastPlayer::clear_has_zhadan_count() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgRunFastPlayer::clear_zhadan_count() {
  zhadan_count_ = 0u;
  clear_has_zhadan_count();
}
inline ::google::protobuf::uint32 MsgRunFastPlayer::zhadan_count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.zhadan_count)
  return zhadan_count_;
}
inline void MsgRunFastPlayer::set_zhadan_count(::google::protobuf::uint32 value) {
  set_has_zhadan_count();
  zhadan_count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastPlayer.zhadan_count)
}

// optional int64 score = 7;
inline bool MsgRunFastPlayer::has_score() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MsgRunFastPlayer::set_has_score() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MsgRunFastPlayer::clear_has_score() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MsgRunFastPlayer::clear_score() {
  score_ = GOOGLE_LONGLONG(0);
  clear_has_score();
}
inline ::google::protobuf::int64 MsgRunFastPlayer::score() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.score)
  return score_;
}
inline void MsgRunFastPlayer::set_score(::google::protobuf::int64 value) {
  set_has_score();
  score_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastPlayer.score)
}

// optional int64 show_down_score = 8;
inline bool MsgRunFastPlayer::has_show_down_score() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MsgRunFastPlayer::set_has_show_down_score() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MsgRunFastPlayer::clear_has_show_down_score() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MsgRunFastPlayer::clear_show_down_score() {
  show_down_score_ = GOOGLE_LONGLONG(0);
  clear_has_show_down_score();
}
inline ::google::protobuf::int64 MsgRunFastPlayer::show_down_score() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.show_down_score)
  return show_down_score_;
}
inline void MsgRunFastPlayer::set_show_down_score(::google::protobuf::int64 value) {
  set_has_show_down_score();
  show_down_score_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastPlayer.show_down_score)
}

// optional uint32 integral_num = 9;
inline bool MsgRunFastPlayer::has_integral_num() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void MsgRunFastPlayer::set_has_integral_num() {
  _has_bits_[0] |= 0x00000100u;
}
inline void MsgRunFastPlayer::clear_has_integral_num() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void MsgRunFastPlayer::clear_integral_num() {
  integral_num_ = 0u;
  clear_has_integral_num();
}
inline ::google::protobuf::uint32 MsgRunFastPlayer::integral_num() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.integral_num)
  return integral_num_;
}
inline void MsgRunFastPlayer::set_integral_num(::google::protobuf::uint32 value) {
  set_has_integral_num();
  integral_num_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastPlayer.integral_num)
}

// repeated .MsgRunFastCardInfo out_card = 10;
inline int MsgRunFastPlayer::out_card_size() const {
  return out_card_.size();
}
inline void MsgRunFastPlayer::clear_out_card() {
  out_card_.Clear();
}
inline const ::MsgRunFastCardInfo& MsgRunFastPlayer::out_card(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.out_card)
  return out_card_.Get(index);
}
inline ::MsgRunFastCardInfo* MsgRunFastPlayer::mutable_out_card(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastPlayer.out_card)
  return out_card_.Mutable(index);
}
inline ::MsgRunFastCardInfo* MsgRunFastPlayer::add_out_card() {
  // @@protoc_insertion_point(field_add:MsgRunFastPlayer.out_card)
  return out_card_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >&
MsgRunFastPlayer::out_card() const {
  // @@protoc_insertion_point(field_list:MsgRunFastPlayer.out_card)
  return out_card_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >*
MsgRunFastPlayer::mutable_out_card() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastPlayer.out_card)
  return &out_card_;
}

// optional uint32 out_type = 11;
inline bool MsgRunFastPlayer::has_out_type() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void MsgRunFastPlayer::set_has_out_type() {
  _has_bits_[0] |= 0x00000400u;
}
inline void MsgRunFastPlayer::clear_has_out_type() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void MsgRunFastPlayer::clear_out_type() {
  out_type_ = 0u;
  clear_has_out_type();
}
inline ::google::protobuf::uint32 MsgRunFastPlayer::out_type() const {
  // @@protoc_insertion_point(field_get:MsgRunFastPlayer.out_type)
  return out_type_;
}
inline void MsgRunFastPlayer::set_out_type(::google::protobuf::uint32 value) {
  set_has_out_type();
  out_type_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastPlayer.out_type)
}

// -------------------------------------------------------------------

// MsgRunFastCardInfo

// optional uint32 card = 1;
inline bool MsgRunFastCardInfo::has_card() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastCardInfo::set_has_card() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastCardInfo::clear_has_card() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastCardInfo::clear_card() {
  card_ = 0u;
  clear_has_card();
}
inline ::google::protobuf::uint32 MsgRunFastCardInfo::card() const {
  // @@protoc_insertion_point(field_get:MsgRunFastCardInfo.card)
  return card_;
}
inline void MsgRunFastCardInfo::set_card(::google::protobuf::uint32 value) {
  set_has_card();
  card_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastCardInfo.card)
}

// -------------------------------------------------------------------

// MsgRunFastActon

// optional uint64 new_actionid = 1;
inline bool MsgRunFastActon::has_new_actionid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastActon::set_has_new_actionid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastActon::clear_has_new_actionid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastActon::clear_new_actionid() {
  new_actionid_ = GOOGLE_ULONGLONG(0);
  clear_has_new_actionid();
}
inline ::google::protobuf::uint64 MsgRunFastActon::new_actionid() const {
  // @@protoc_insertion_point(field_get:MsgRunFastActon.new_actionid)
  return new_actionid_;
}
inline void MsgRunFastActon::set_new_actionid(::google::protobuf::uint64 value) {
  set_has_new_actionid();
  new_actionid_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastActon.new_actionid)
}

// optional uint64 old_actionid = 2;
inline bool MsgRunFastActon::has_old_actionid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRunFastActon::set_has_old_actionid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRunFastActon::clear_has_old_actionid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRunFastActon::clear_old_actionid() {
  old_actionid_ = GOOGLE_ULONGLONG(0);
  clear_has_old_actionid();
}
inline ::google::protobuf::uint64 MsgRunFastActon::old_actionid() const {
  // @@protoc_insertion_point(field_get:MsgRunFastActon.old_actionid)
  return old_actionid_;
}
inline void MsgRunFastActon::set_old_actionid(::google::protobuf::uint64 value) {
  set_has_old_actionid();
  old_actionid_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastActon.old_actionid)
}

// repeated .MsgRunFastCardInfo last_out_card = 3;
inline int MsgRunFastActon::last_out_card_size() const {
  return last_out_card_.size();
}
inline void MsgRunFastActon::clear_last_out_card() {
  last_out_card_.Clear();
}
inline const ::MsgRunFastCardInfo& MsgRunFastActon::last_out_card(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastActon.last_out_card)
  return last_out_card_.Get(index);
}
inline ::MsgRunFastCardInfo* MsgRunFastActon::mutable_last_out_card(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastActon.last_out_card)
  return last_out_card_.Mutable(index);
}
inline ::MsgRunFastCardInfo* MsgRunFastActon::add_last_out_card() {
  // @@protoc_insertion_point(field_add:MsgRunFastActon.last_out_card)
  return last_out_card_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >&
MsgRunFastActon::last_out_card() const {
  // @@protoc_insertion_point(field_list:MsgRunFastActon.last_out_card)
  return last_out_card_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >*
MsgRunFastActon::mutable_last_out_card() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastActon.last_out_card)
  return &last_out_card_;
}

// optional uint32 last_out_type = 4;
inline bool MsgRunFastActon::has_last_out_type() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgRunFastActon::set_has_last_out_type() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgRunFastActon::clear_has_last_out_type() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgRunFastActon::clear_last_out_type() {
  last_out_type_ = 0u;
  clear_has_last_out_type();
}
inline ::google::protobuf::uint32 MsgRunFastActon::last_out_type() const {
  // @@protoc_insertion_point(field_get:MsgRunFastActon.last_out_type)
  return last_out_type_;
}
inline void MsgRunFastActon::set_last_out_type(::google::protobuf::uint32 value) {
  set_has_last_out_type();
  last_out_type_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastActon.last_out_type)
}

// optional uint32 wik = 5;
inline bool MsgRunFastActon::has_wik() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgRunFastActon::set_has_wik() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgRunFastActon::clear_has_wik() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgRunFastActon::clear_wik() {
  wik_ = 0u;
  clear_has_wik();
}
inline ::google::protobuf::uint32 MsgRunFastActon::wik() const {
  // @@protoc_insertion_point(field_get:MsgRunFastActon.wik)
  return wik_;
}
inline void MsgRunFastActon::set_wik(::google::protobuf::uint32 value) {
  set_has_wik();
  wik_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastActon.wik)
}

// repeated .MsgRunFastPlayer player_list = 6;
inline int MsgRunFastActon::player_list_size() const {
  return player_list_.size();
}
inline void MsgRunFastActon::clear_player_list() {
  player_list_.Clear();
}
inline const ::MsgRunFastPlayer& MsgRunFastActon::player_list(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastActon.player_list)
  return player_list_.Get(index);
}
inline ::MsgRunFastPlayer* MsgRunFastActon::mutable_player_list(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastActon.player_list)
  return player_list_.Mutable(index);
}
inline ::MsgRunFastPlayer* MsgRunFastActon::add_player_list() {
  // @@protoc_insertion_point(field_add:MsgRunFastActon.player_list)
  return player_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >&
MsgRunFastActon::player_list() const {
  // @@protoc_insertion_point(field_list:MsgRunFastActon.player_list)
  return player_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >*
MsgRunFastActon::mutable_player_list() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastActon.player_list)
  return &player_list_;
}

// -------------------------------------------------------------------

// MsgRunFastUserOutCard

// optional uint64 old_actionid = 1;
inline bool MsgRunFastUserOutCard::has_old_actionid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastUserOutCard::set_has_old_actionid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastUserOutCard::clear_has_old_actionid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastUserOutCard::clear_old_actionid() {
  old_actionid_ = GOOGLE_ULONGLONG(0);
  clear_has_old_actionid();
}
inline ::google::protobuf::uint64 MsgRunFastUserOutCard::old_actionid() const {
  // @@protoc_insertion_point(field_get:MsgRunFastUserOutCard.old_actionid)
  return old_actionid_;
}
inline void MsgRunFastUserOutCard::set_old_actionid(::google::protobuf::uint64 value) {
  set_has_old_actionid();
  old_actionid_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastUserOutCard.old_actionid)
}

// optional uint32 out_type = 2;
inline bool MsgRunFastUserOutCard::has_out_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRunFastUserOutCard::set_has_out_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRunFastUserOutCard::clear_has_out_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRunFastUserOutCard::clear_out_type() {
  out_type_ = 0u;
  clear_has_out_type();
}
inline ::google::protobuf::uint32 MsgRunFastUserOutCard::out_type() const {
  // @@protoc_insertion_point(field_get:MsgRunFastUserOutCard.out_type)
  return out_type_;
}
inline void MsgRunFastUserOutCard::set_out_type(::google::protobuf::uint32 value) {
  set_has_out_type();
  out_type_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastUserOutCard.out_type)
}

// optional uint32 hand_count = 3;
inline bool MsgRunFastUserOutCard::has_hand_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgRunFastUserOutCard::set_has_hand_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgRunFastUserOutCard::clear_has_hand_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgRunFastUserOutCard::clear_hand_count() {
  hand_count_ = 0u;
  clear_has_hand_count();
}
inline ::google::protobuf::uint32 MsgRunFastUserOutCard::hand_count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastUserOutCard.hand_count)
  return hand_count_;
}
inline void MsgRunFastUserOutCard::set_hand_count(::google::protobuf::uint32 value) {
  set_has_hand_count();
  hand_count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastUserOutCard.hand_count)
}

// repeated uint32 outcard_laiziLogic = 4;
inline int MsgRunFastUserOutCard::outcard_laizilogic_size() const {
  return outcard_laizilogic_.size();
}
inline void MsgRunFastUserOutCard::clear_outcard_laizilogic() {
  outcard_laizilogic_.Clear();
}
inline ::google::protobuf::uint32 MsgRunFastUserOutCard::outcard_laizilogic(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastUserOutCard.outcard_laiziLogic)
  return outcard_laizilogic_.Get(index);
}
inline void MsgRunFastUserOutCard::set_outcard_laizilogic(int index, ::google::protobuf::uint32 value) {
  outcard_laizilogic_.Set(index, value);
  // @@protoc_insertion_point(field_set:MsgRunFastUserOutCard.outcard_laiziLogic)
}
inline void MsgRunFastUserOutCard::add_outcard_laizilogic(::google::protobuf::uint32 value) {
  outcard_laizilogic_.Add(value);
  // @@protoc_insertion_point(field_add:MsgRunFastUserOutCard.outcard_laiziLogic)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
MsgRunFastUserOutCard::outcard_laizilogic() const {
  // @@protoc_insertion_point(field_list:MsgRunFastUserOutCard.outcard_laiziLogic)
  return outcard_laizilogic_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
MsgRunFastUserOutCard::mutable_outcard_laizilogic() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastUserOutCard.outcard_laiziLogic)
  return &outcard_laizilogic_;
}

// repeated .MsgRunFastCardInfo out_card = 5;
inline int MsgRunFastUserOutCard::out_card_size() const {
  return out_card_.size();
}
inline void MsgRunFastUserOutCard::clear_out_card() {
  out_card_.Clear();
}
inline const ::MsgRunFastCardInfo& MsgRunFastUserOutCard::out_card(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastUserOutCard.out_card)
  return out_card_.Get(index);
}
inline ::MsgRunFastCardInfo* MsgRunFastUserOutCard::mutable_out_card(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastUserOutCard.out_card)
  return out_card_.Mutable(index);
}
inline ::MsgRunFastCardInfo* MsgRunFastUserOutCard::add_out_card() {
  // @@protoc_insertion_point(field_add:MsgRunFastUserOutCard.out_card)
  return out_card_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >&
MsgRunFastUserOutCard::out_card() const {
  // @@protoc_insertion_point(field_list:MsgRunFastUserOutCard.out_card)
  return out_card_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastCardInfo >*
MsgRunFastUserOutCard::mutable_out_card() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastUserOutCard.out_card)
  return &out_card_;
}

// optional bool is_baodan = 6;
inline bool MsgRunFastUserOutCard::has_is_baodan() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgRunFastUserOutCard::set_has_is_baodan() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgRunFastUserOutCard::clear_has_is_baodan() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgRunFastUserOutCard::clear_is_baodan() {
  is_baodan_ = false;
  clear_has_is_baodan();
}
inline bool MsgRunFastUserOutCard::is_baodan() const {
  // @@protoc_insertion_point(field_get:MsgRunFastUserOutCard.is_baodan)
  return is_baodan_;
}
inline void MsgRunFastUserOutCard::set_is_baodan(bool value) {
  set_has_is_baodan();
  is_baodan_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastUserOutCard.is_baodan)
}

// -------------------------------------------------------------------

// MsgRunFastMSGRoomParam

// optional uint32 room_run_time = 1;
inline bool MsgRunFastMSGRoomParam::has_room_run_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastMSGRoomParam::set_has_room_run_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastMSGRoomParam::clear_has_room_run_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastMSGRoomParam::clear_room_run_time() {
  room_run_time_ = 0u;
  clear_has_room_run_time();
}
inline ::google::protobuf::uint32 MsgRunFastMSGRoomParam::room_run_time() const {
  // @@protoc_insertion_point(field_get:MsgRunFastMSGRoomParam.room_run_time)
  return room_run_time_;
}
inline void MsgRunFastMSGRoomParam::set_room_run_time(::google::protobuf::uint32 value) {
  set_has_room_run_time();
  room_run_time_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastMSGRoomParam.room_run_time)
}

// optional uint32 room_param = 2;
inline bool MsgRunFastMSGRoomParam::has_room_param() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRunFastMSGRoomParam::set_has_room_param() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRunFastMSGRoomParam::clear_has_room_param() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRunFastMSGRoomParam::clear_room_param() {
  room_param_ = 0u;
  clear_has_room_param();
}
inline ::google::protobuf::uint32 MsgRunFastMSGRoomParam::room_param() const {
  // @@protoc_insertion_point(field_get:MsgRunFastMSGRoomParam.room_param)
  return room_param_;
}
inline void MsgRunFastMSGRoomParam::set_room_param(::google::protobuf::uint32 value) {
  set_has_room_param();
  room_param_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastMSGRoomParam.room_param)
}

// -------------------------------------------------------------------

// MsgRunFastRoom

// optional .TRunFastState room_state = 1;
inline bool MsgRunFastRoom::has_room_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastRoom::set_has_room_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastRoom::clear_has_room_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastRoom::clear_room_state() {
  room_state_ = 0;
  clear_has_room_state();
}
inline ::TRunFastState MsgRunFastRoom::room_state() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.room_state)
  return static_cast< ::TRunFastState >(room_state_);
}
inline void MsgRunFastRoom::set_room_state(::TRunFastState value) {
  assert(::TRunFastState_IsValid(value));
  set_has_room_state();
  room_state_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoom.room_state)
}

// optional uint32 state_time = 2;
inline bool MsgRunFastRoom::has_state_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRunFastRoom::set_has_state_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRunFastRoom::clear_has_state_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRunFastRoom::clear_state_time() {
  state_time_ = 0u;
  clear_has_state_time();
}
inline ::google::protobuf::uint32 MsgRunFastRoom::state_time() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.state_time)
  return state_time_;
}
inline void MsgRunFastRoom::set_state_time(::google::protobuf::uint32 value) {
  set_has_state_time();
  state_time_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoom.state_time)
}

// repeated .MsgRunFastPlayer player_list = 3;
inline int MsgRunFastRoom::player_list_size() const {
  return player_list_.size();
}
inline void MsgRunFastRoom::clear_player_list() {
  player_list_.Clear();
}
inline const ::MsgRunFastPlayer& MsgRunFastRoom::player_list(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.player_list)
  return player_list_.Get(index);
}
inline ::MsgRunFastPlayer* MsgRunFastRoom::mutable_player_list(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastRoom.player_list)
  return player_list_.Mutable(index);
}
inline ::MsgRunFastPlayer* MsgRunFastRoom::add_player_list() {
  // @@protoc_insertion_point(field_add:MsgRunFastRoom.player_list)
  return player_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >&
MsgRunFastRoom::player_list() const {
  // @@protoc_insertion_point(field_list:MsgRunFastRoom.player_list)
  return player_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >*
MsgRunFastRoom::mutable_player_list() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastRoom.player_list)
  return &player_list_;
}

// optional uint64 action_id = 4;
inline bool MsgRunFastRoom::has_action_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgRunFastRoom::set_has_action_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgRunFastRoom::clear_has_action_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgRunFastRoom::clear_action_id() {
  action_id_ = GOOGLE_ULONGLONG(0);
  clear_has_action_id();
}
inline ::google::protobuf::uint64 MsgRunFastRoom::action_id() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.action_id)
  return action_id_;
}
inline void MsgRunFastRoom::set_action_id(::google::protobuf::uint64 value) {
  set_has_action_id();
  action_id_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoom.action_id)
}

// optional uint64 room_id = 5;
inline bool MsgRunFastRoom::has_room_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgRunFastRoom::set_has_room_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgRunFastRoom::clear_has_room_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgRunFastRoom::clear_room_id() {
  room_id_ = GOOGLE_ULONGLONG(0);
  clear_has_room_id();
}
inline ::google::protobuf::uint64 MsgRunFastRoom::room_id() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.room_id)
  return room_id_;
}
inline void MsgRunFastRoom::set_room_id(::google::protobuf::uint64 value) {
  set_has_room_id();
  room_id_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoom.room_id)
}

// optional uint32 game_count = 6;
inline bool MsgRunFastRoom::has_game_count() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgRunFastRoom::set_has_game_count() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgRunFastRoom::clear_has_game_count() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgRunFastRoom::clear_game_count() {
  game_count_ = 0u;
  clear_has_game_count();
}
inline ::google::protobuf::uint32 MsgRunFastRoom::game_count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.game_count)
  return game_count_;
}
inline void MsgRunFastRoom::set_game_count(::google::protobuf::uint32 value) {
  set_has_game_count();
  game_count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoom.game_count)
}

// optional .MsgCreatePrivateRoom private_room = 7;
inline bool MsgRunFastRoom::has_private_room() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MsgRunFastRoom::set_has_private_room() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MsgRunFastRoom::clear_has_private_room() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MsgRunFastRoom::clear_private_room() {
  if (private_room_ != NULL) private_room_->::MsgCreatePrivateRoom::Clear();
  clear_has_private_room();
}
inline const ::MsgCreatePrivateRoom& MsgRunFastRoom::private_room() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.private_room)
  return private_room_ != NULL ? *private_room_ : *default_instance_->private_room_;
}
inline ::MsgCreatePrivateRoom* MsgRunFastRoom::mutable_private_room() {
  set_has_private_room();
  if (private_room_ == NULL) private_room_ = new ::MsgCreatePrivateRoom;
  // @@protoc_insertion_point(field_mutable:MsgRunFastRoom.private_room)
  return private_room_;
}
inline ::MsgCreatePrivateRoom* MsgRunFastRoom::release_private_room() {
  clear_has_private_room();
  ::MsgCreatePrivateRoom* temp = private_room_;
  private_room_ = NULL;
  return temp;
}
inline void MsgRunFastRoom::set_allocated_private_room(::MsgCreatePrivateRoom* private_room) {
  delete private_room_;
  private_room_ = private_room;
  if (private_room) {
    set_has_private_room();
  } else {
    clear_has_private_room();
  }
  // @@protoc_insertion_point(field_set_allocated:MsgRunFastRoom.private_room)
}

// optional .MsgRunFastUserOutCard last_outcard = 8;
inline bool MsgRunFastRoom::has_last_outcard() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void MsgRunFastRoom::set_has_last_outcard() {
  _has_bits_[0] |= 0x00000080u;
}
inline void MsgRunFastRoom::clear_has_last_outcard() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void MsgRunFastRoom::clear_last_outcard() {
  if (last_outcard_ != NULL) last_outcard_->::MsgRunFastUserOutCard::Clear();
  clear_has_last_outcard();
}
inline const ::MsgRunFastUserOutCard& MsgRunFastRoom::last_outcard() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.last_outcard)
  return last_outcard_ != NULL ? *last_outcard_ : *default_instance_->last_outcard_;
}
inline ::MsgRunFastUserOutCard* MsgRunFastRoom::mutable_last_outcard() {
  set_has_last_outcard();
  if (last_outcard_ == NULL) last_outcard_ = new ::MsgRunFastUserOutCard;
  // @@protoc_insertion_point(field_mutable:MsgRunFastRoom.last_outcard)
  return last_outcard_;
}
inline ::MsgRunFastUserOutCard* MsgRunFastRoom::release_last_outcard() {
  clear_has_last_outcard();
  ::MsgRunFastUserOutCard* temp = last_outcard_;
  last_outcard_ = NULL;
  return temp;
}
inline void MsgRunFastRoom::set_allocated_last_outcard(::MsgRunFastUserOutCard* last_outcard) {
  delete last_outcard_;
  last_outcard_ = last_outcard;
  if (last_outcard) {
    set_has_last_outcard();
  } else {
    clear_has_last_outcard();
  }
  // @@protoc_insertion_point(field_set_allocated:MsgRunFastRoom.last_outcard)
}

// optional uint32 wik = 10;
inline bool MsgRunFastRoom::has_wik() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void MsgRunFastRoom::set_has_wik() {
  _has_bits_[0] |= 0x00000100u;
}
inline void MsgRunFastRoom::clear_has_wik() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void MsgRunFastRoom::clear_wik() {
  wik_ = 0u;
  clear_has_wik();
}
inline ::google::protobuf::uint32 MsgRunFastRoom::wik() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.wik)
  return wik_;
}
inline void MsgRunFastRoom::set_wik(::google::protobuf::uint32 value) {
  set_has_wik();
  wik_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoom.wik)
}

// optional uint32 room_pay_type = 11;
inline bool MsgRunFastRoom::has_room_pay_type() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void MsgRunFastRoom::set_has_room_pay_type() {
  _has_bits_[0] |= 0x00000200u;
}
inline void MsgRunFastRoom::clear_has_room_pay_type() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void MsgRunFastRoom::clear_room_pay_type() {
  room_pay_type_ = 0u;
  clear_has_room_pay_type();
}
inline ::google::protobuf::uint32 MsgRunFastRoom::room_pay_type() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.room_pay_type)
  return room_pay_type_;
}
inline void MsgRunFastRoom::set_room_pay_type(::google::protobuf::uint32 value) {
  set_has_room_pay_type();
  room_pay_type_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoom.room_pay_type)
}

// optional .MsgRunFastMSGRoomParam msg_room_param = 12;
inline bool MsgRunFastRoom::has_msg_room_param() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void MsgRunFastRoom::set_has_msg_room_param() {
  _has_bits_[0] |= 0x00000400u;
}
inline void MsgRunFastRoom::clear_has_msg_room_param() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void MsgRunFastRoom::clear_msg_room_param() {
  if (msg_room_param_ != NULL) msg_room_param_->::MsgRunFastMSGRoomParam::Clear();
  clear_has_msg_room_param();
}
inline const ::MsgRunFastMSGRoomParam& MsgRunFastRoom::msg_room_param() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoom.msg_room_param)
  return msg_room_param_ != NULL ? *msg_room_param_ : *default_instance_->msg_room_param_;
}
inline ::MsgRunFastMSGRoomParam* MsgRunFastRoom::mutable_msg_room_param() {
  set_has_msg_room_param();
  if (msg_room_param_ == NULL) msg_room_param_ = new ::MsgRunFastMSGRoomParam;
  // @@protoc_insertion_point(field_mutable:MsgRunFastRoom.msg_room_param)
  return msg_room_param_;
}
inline ::MsgRunFastMSGRoomParam* MsgRunFastRoom::release_msg_room_param() {
  clear_has_msg_room_param();
  ::MsgRunFastMSGRoomParam* temp = msg_room_param_;
  msg_room_param_ = NULL;
  return temp;
}
inline void MsgRunFastRoom::set_allocated_msg_room_param(::MsgRunFastMSGRoomParam* msg_room_param) {
  delete msg_room_param_;
  msg_room_param_ = msg_room_param;
  if (msg_room_param) {
    set_has_msg_room_param();
  } else {
    clear_has_msg_room_param();
  }
  // @@protoc_insertion_point(field_set_allocated:MsgRunFastRoom.msg_room_param)
}

// -------------------------------------------------------------------

// MsgRunFastGameOverInfo

// optional uint64 role_id = 1;
inline bool MsgRunFastGameOverInfo::has_role_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastGameOverInfo::set_has_role_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastGameOverInfo::clear_has_role_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastGameOverInfo::clear_role_id() {
  role_id_ = GOOGLE_ULONGLONG(0);
  clear_has_role_id();
}
inline ::google::protobuf::uint64 MsgRunFastGameOverInfo::role_id() const {
  // @@protoc_insertion_point(field_get:MsgRunFastGameOverInfo.role_id)
  return role_id_;
}
inline void MsgRunFastGameOverInfo::set_role_id(::google::protobuf::uint64 value) {
  set_has_role_id();
  role_id_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastGameOverInfo.role_id)
}

// optional int64 max_score = 2;
inline bool MsgRunFastGameOverInfo::has_max_score() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRunFastGameOverInfo::set_has_max_score() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRunFastGameOverInfo::clear_has_max_score() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRunFastGameOverInfo::clear_max_score() {
  max_score_ = GOOGLE_LONGLONG(0);
  clear_has_max_score();
}
inline ::google::protobuf::int64 MsgRunFastGameOverInfo::max_score() const {
  // @@protoc_insertion_point(field_get:MsgRunFastGameOverInfo.max_score)
  return max_score_;
}
inline void MsgRunFastGameOverInfo::set_max_score(::google::protobuf::int64 value) {
  set_has_max_score();
  max_score_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastGameOverInfo.max_score)
}

// optional uint32 zhadan_count = 3;
inline bool MsgRunFastGameOverInfo::has_zhadan_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MsgRunFastGameOverInfo::set_has_zhadan_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MsgRunFastGameOverInfo::clear_has_zhadan_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MsgRunFastGameOverInfo::clear_zhadan_count() {
  zhadan_count_ = 0u;
  clear_has_zhadan_count();
}
inline ::google::protobuf::uint32 MsgRunFastGameOverInfo::zhadan_count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastGameOverInfo.zhadan_count)
  return zhadan_count_;
}
inline void MsgRunFastGameOverInfo::set_zhadan_count(::google::protobuf::uint32 value) {
  set_has_zhadan_count();
  zhadan_count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastGameOverInfo.zhadan_count)
}

// optional uint32 win_count = 4;
inline bool MsgRunFastGameOverInfo::has_win_count() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgRunFastGameOverInfo::set_has_win_count() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgRunFastGameOverInfo::clear_has_win_count() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgRunFastGameOverInfo::clear_win_count() {
  win_count_ = 0u;
  clear_has_win_count();
}
inline ::google::protobuf::uint32 MsgRunFastGameOverInfo::win_count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastGameOverInfo.win_count)
  return win_count_;
}
inline void MsgRunFastGameOverInfo::set_win_count(::google::protobuf::uint32 value) {
  set_has_win_count();
  win_count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastGameOverInfo.win_count)
}

// optional uint32 lose_count = 5;
inline bool MsgRunFastGameOverInfo::has_lose_count() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgRunFastGameOverInfo::set_has_lose_count() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgRunFastGameOverInfo::clear_has_lose_count() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgRunFastGameOverInfo::clear_lose_count() {
  lose_count_ = 0u;
  clear_has_lose_count();
}
inline ::google::protobuf::uint32 MsgRunFastGameOverInfo::lose_count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastGameOverInfo.lose_count)
  return lose_count_;
}
inline void MsgRunFastGameOverInfo::set_lose_count(::google::protobuf::uint32 value) {
  set_has_lose_count();
  lose_count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastGameOverInfo.lose_count)
}

// -------------------------------------------------------------------

// MsgRunFastRoomShowDown

// optional .TRunFastState room_state = 1;
inline bool MsgRunFastRoomShowDown::has_room_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastRoomShowDown::set_has_room_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastRoomShowDown::clear_has_room_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastRoomShowDown::clear_room_state() {
  room_state_ = 0;
  clear_has_room_state();
}
inline ::TRunFastState MsgRunFastRoomShowDown::room_state() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoomShowDown.room_state)
  return static_cast< ::TRunFastState >(room_state_);
}
inline void MsgRunFastRoomShowDown::set_room_state(::TRunFastState value) {
  assert(::TRunFastState_IsValid(value));
  set_has_room_state();
  room_state_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoomShowDown.room_state)
}

// optional uint32 state_time = 2;
inline bool MsgRunFastRoomShowDown::has_state_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRunFastRoomShowDown::set_has_state_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRunFastRoomShowDown::clear_has_state_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRunFastRoomShowDown::clear_state_time() {
  state_time_ = 0u;
  clear_has_state_time();
}
inline ::google::protobuf::uint32 MsgRunFastRoomShowDown::state_time() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoomShowDown.state_time)
  return state_time_;
}
inline void MsgRunFastRoomShowDown::set_state_time(::google::protobuf::uint32 value) {
  set_has_state_time();
  state_time_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoomShowDown.state_time)
}

// repeated .MsgRunFastPlayer player_list = 3;
inline int MsgRunFastRoomShowDown::player_list_size() const {
  return player_list_.size();
}
inline void MsgRunFastRoomShowDown::clear_player_list() {
  player_list_.Clear();
}
inline const ::MsgRunFastPlayer& MsgRunFastRoomShowDown::player_list(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoomShowDown.player_list)
  return player_list_.Get(index);
}
inline ::MsgRunFastPlayer* MsgRunFastRoomShowDown::mutable_player_list(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastRoomShowDown.player_list)
  return player_list_.Mutable(index);
}
inline ::MsgRunFastPlayer* MsgRunFastRoomShowDown::add_player_list() {
  // @@protoc_insertion_point(field_add:MsgRunFastRoomShowDown.player_list)
  return player_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >&
MsgRunFastRoomShowDown::player_list() const {
  // @@protoc_insertion_point(field_list:MsgRunFastRoomShowDown.player_list)
  return player_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastPlayer >*
MsgRunFastRoomShowDown::mutable_player_list() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastRoomShowDown.player_list)
  return &player_list_;
}

// optional uint64 room_id = 4;
inline bool MsgRunFastRoomShowDown::has_room_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MsgRunFastRoomShowDown::set_has_room_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MsgRunFastRoomShowDown::clear_has_room_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MsgRunFastRoomShowDown::clear_room_id() {
  room_id_ = GOOGLE_ULONGLONG(0);
  clear_has_room_id();
}
inline ::google::protobuf::uint64 MsgRunFastRoomShowDown::room_id() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoomShowDown.room_id)
  return room_id_;
}
inline void MsgRunFastRoomShowDown::set_room_id(::google::protobuf::uint64 value) {
  set_has_room_id();
  room_id_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoomShowDown.room_id)
}

// optional uint32 game_count = 5;
inline bool MsgRunFastRoomShowDown::has_game_count() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MsgRunFastRoomShowDown::set_has_game_count() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MsgRunFastRoomShowDown::clear_has_game_count() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MsgRunFastRoomShowDown::clear_game_count() {
  game_count_ = 0u;
  clear_has_game_count();
}
inline ::google::protobuf::uint32 MsgRunFastRoomShowDown::game_count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoomShowDown.game_count)
  return game_count_;
}
inline void MsgRunFastRoomShowDown::set_game_count(::google::protobuf::uint32 value) {
  set_has_game_count();
  game_count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoomShowDown.game_count)
}

// optional uint32 time = 6;
inline bool MsgRunFastRoomShowDown::has_time() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MsgRunFastRoomShowDown::set_has_time() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MsgRunFastRoomShowDown::clear_has_time() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MsgRunFastRoomShowDown::clear_time() {
  time_ = 0u;
  clear_has_time();
}
inline ::google::protobuf::uint32 MsgRunFastRoomShowDown::time() const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoomShowDown.time)
  return time_;
}
inline void MsgRunFastRoomShowDown::set_time(::google::protobuf::uint32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastRoomShowDown.time)
}

// repeated .MsgRunFastGameOverInfo over_info = 7;
inline int MsgRunFastRoomShowDown::over_info_size() const {
  return over_info_.size();
}
inline void MsgRunFastRoomShowDown::clear_over_info() {
  over_info_.Clear();
}
inline const ::MsgRunFastGameOverInfo& MsgRunFastRoomShowDown::over_info(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoomShowDown.over_info)
  return over_info_.Get(index);
}
inline ::MsgRunFastGameOverInfo* MsgRunFastRoomShowDown::mutable_over_info(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastRoomShowDown.over_info)
  return over_info_.Mutable(index);
}
inline ::MsgRunFastGameOverInfo* MsgRunFastRoomShowDown::add_over_info() {
  // @@protoc_insertion_point(field_add:MsgRunFastRoomShowDown.over_info)
  return over_info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastGameOverInfo >&
MsgRunFastRoomShowDown::over_info() const {
  // @@protoc_insertion_point(field_list:MsgRunFastRoomShowDown.over_info)
  return over_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastGameOverInfo >*
MsgRunFastRoomShowDown::mutable_over_info() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastRoomShowDown.over_info)
  return &over_info_;
}

// repeated .MsgRunFastIntegralCount integral_list = 8;
inline int MsgRunFastRoomShowDown::integral_list_size() const {
  return integral_list_.size();
}
inline void MsgRunFastRoomShowDown::clear_integral_list() {
  integral_list_.Clear();
}
inline const ::MsgRunFastIntegralCount& MsgRunFastRoomShowDown::integral_list(int index) const {
  // @@protoc_insertion_point(field_get:MsgRunFastRoomShowDown.integral_list)
  return integral_list_.Get(index);
}
inline ::MsgRunFastIntegralCount* MsgRunFastRoomShowDown::mutable_integral_list(int index) {
  // @@protoc_insertion_point(field_mutable:MsgRunFastRoomShowDown.integral_list)
  return integral_list_.Mutable(index);
}
inline ::MsgRunFastIntegralCount* MsgRunFastRoomShowDown::add_integral_list() {
  // @@protoc_insertion_point(field_add:MsgRunFastRoomShowDown.integral_list)
  return integral_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::MsgRunFastIntegralCount >&
MsgRunFastRoomShowDown::integral_list() const {
  // @@protoc_insertion_point(field_list:MsgRunFastRoomShowDown.integral_list)
  return integral_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::MsgRunFastIntegralCount >*
MsgRunFastRoomShowDown::mutable_integral_list() {
  // @@protoc_insertion_point(field_mutable_list:MsgRunFastRoomShowDown.integral_list)
  return &integral_list_;
}

// -------------------------------------------------------------------

// MsgRunFastIntegralCount

// optional uint64 roleid = 1;
inline bool MsgRunFastIntegralCount::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MsgRunFastIntegralCount::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MsgRunFastIntegralCount::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MsgRunFastIntegralCount::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
  clear_has_roleid();
}
inline ::google::protobuf::uint64 MsgRunFastIntegralCount::roleid() const {
  // @@protoc_insertion_point(field_get:MsgRunFastIntegralCount.roleid)
  return roleid_;
}
inline void MsgRunFastIntegralCount::set_roleid(::google::protobuf::uint64 value) {
  set_has_roleid();
  roleid_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastIntegralCount.roleid)
}

// optional uint32 count = 2;
inline bool MsgRunFastIntegralCount::has_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MsgRunFastIntegralCount::set_has_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MsgRunFastIntegralCount::clear_has_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MsgRunFastIntegralCount::clear_count() {
  count_ = 0u;
  clear_has_count();
}
inline ::google::protobuf::uint32 MsgRunFastIntegralCount::count() const {
  // @@protoc_insertion_point(field_get:MsgRunFastIntegralCount.count)
  return count_;
}
inline void MsgRunFastIntegralCount::set_count(::google::protobuf::uint32 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:MsgRunFastIntegralCount.count)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::TRunFastPlayerWik> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TRunFastPlayerWik>() {
  return ::TRunFastPlayerWik_descriptor();
}
template <> struct is_proto_enum< ::TRunFastPlayerState> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TRunFastPlayerState>() {
  return ::TRunFastPlayerState_descriptor();
}
template <> struct is_proto_enum< ::TRunFastState> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TRunFastState>() {
  return ::TRunFastState_descriptor();
}
template <> struct is_proto_enum< ::TRunFastCT> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::TRunFastCT>() {
  return ::TRunFastCT_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5frunfast_2eproto__INCLUDED
