#ifndef send_logic_h__
#define send_logic_h__
#include <nel/misc/sstring.h>
#include <game_share/game_def.h>
#include <nel/misc/types_nl.h>
#include <nel/misc/random.h>

class CConnect;

class SendLogic
{
public:
    SendLogic( CConnect* );
    ~SendLogic( void );

    // 登陆玩家;
    void SendLogin( NLMISC::CSString token );
    // 请求玩家基础信息;
    void SendPlayerInfo( void );
    // 请求加载玩家实体数据;
    //void SendPlayerEntity( MsgSyncDataCheckSum& );
    // 请求创建角色;
    void SendCreateRole( void );

    // 请求进入房间;
    void EnterGame( void );
    // 请求离开房间;
    void LeaveRoom( void );
    // 请求刷新玩家信息;
    void SyncPlayerInfo( void );
    // 请求游戏币排行榜（前十名）;
    void MoneyRanking( void );
    // 请求下注;
    void BlackJackAddPour( int rand_count, int rand_pour );
    // 请求要牌;
    void BlackJackAskCard( void );
    // 请求分牌;
    void BlackJackSplitCard( void );
    // 请求停牌;
    void BlackJackStandCard( void );
    // 购买保险;
    void BlackJackBuySurrender( void );
    // 跳过保险;
    void BlackJackSkipSurrender( void );
    // 双倍;
    void BlackJackDoubleCard( void );
    // 清除下注;
    void BlackJackClearPour( void );
    // 添加金钱;
    void PlayerAddMoney( void );
    // 减少金钱;
    void PlayerSubMoney( void );
    // 领取奖励;
    void GetReward( void );
    // 请求比赛数据;
    void GetChampionship( void );
    // 请求比赛奖池;
    void RequestPrizePool( void );
    // Ranking Room Top;
    void RankingRoomTop( void );
    // 请求获取自己的排行榜数据;
    void GetRankingMyData( void );
    // 请求发送普通邮件;
    void RequestSendCommmonMail( int rand_title_count , int rand_content_count );
    // 请求邮件数据;
    void RequestMailData( void );
    // 请求获取系统邮件奖励;
    void RequestSystemMailReward( void );
    // 请求获取普通邮件奖励;
    void RequestCommonMailReward( void );
    // 请求删除普通邮件;
    void RequestDeleteCommonMail( void );
    // 请求删除系统邮件;
    void RequestDeleteSystemMail( void );
    // 请求查看普通邮件;
    void RequestLookCommonMail( void );
    // 请求同步好友列表;
    void SynchFriendList( void );
    // 请求同步好友申请列表;
    void SynchApplyList( void );
    // 好友申请;
    void AddFriendApply( void );
    // 好友添加;
    void AddFriend( void );
    // 删除好友;
    void DeleteFriend( void );
    // 删除好友申请;
    void DeleteApplyFriend( void );
    // 请求好友详细信息;
    void RequestFriendDetail( void );
    // 请求申请好友详细信息;
    void RequestApplyDetail( void );
    // 请求奖励好友;
    void RequestRewardFriend( int rand_money );
    // 房间内聊天;
    void ChatRoom( int rand_count );
    // 牌桌上打赏;
    void GiveTips( void );
    // 请求同局其它玩家详细信息;
    void RoomPlayerInfo( void );
    // 好友邀请;
    void InviteFriend( void ); 
    // 请求发送系统模板邮件;
    void SendTemplateMail( void );
    // 绑定Facebook;
    void BindFacebook( void );
    // 大转盘;
    void PullRouletteMoney( void );
    // 转倍率;
    void PullRouletteRate( void );
    // 美金转倍率;
    void PullRouletteRateRMB( void );
    // 获取转盘奖励;
    void RouletteGetMoney( void );
    // 请求商店信息;
    void RequestShopInfo( void );
    // 请求购买游戏币;
    void RequestBuyMoney( void );
    // 请求换名字;
    void PlayerRename( void );
    // 请求其他玩家详细信息;
    void ReqOtherPlayerInfo( void );
    // 请求自己详细信息;
    void ReqSelfPlayerInfo( void );
    // 请求其他玩家统计信息;
    void ReqPlayerKPI( void );
    // 大厅看广告领取奖励;
    void HallAdsDrawAward( void );
    // 房间看广告领取奖励;
    void RoomAdsDrawAward( void );
    // 检测消息发送时间;
    void CkeckSendMsgTime( void );
    // 玩家跟注;
    void CallPour(void);
    // 玩家加注;
    void RaisePour(void);
    // 玩家弃牌;
    void FoldCard(void);
    // 玩家让牌;
    void CheckCard(void);
    // 重置筹码;
    void ResetCoins(void);
    // 返回游戏;
    void GoBackGame(void);
    // 老虎机拉杆;
    void SlotsSpin(void);
    // 请求查看邮件状态;
    void CheckMailState(void);
    // 请求BJ比赛参赛人数;
    void SynchRoomRankPlayerNum(void);
    // 请求同步成就信息;
    void SynchAchievementData(void);
    // 请求同步已完成成就信息;
    void SynchCompleteAchievementData(void);
    // 请求领取成就奖励;
    void DrawAchievementReward(void);
    // 重置赌注(Bet, Bet*2, Betall);
    void BlackJackResetPour(int rand_pour);
    // 老虎机小游戏;
    void SlotsBonusGameSelect(void);
    // 推荐好友;
    void RequestRecommendFriend(void);
    // 请求同步统计信息;
    void SynchStatisticsData(void);
    // 更新个性签名;
    void UpdateDynamicMsg( void );
    // 修改头像;
    void ReHeadPortrait( int rand_index );
    // Slots请求奖池数据;
    void GetSlotsJackpots( void );
    // 德州竞技场报名;
    void TPChallApplyGame( void );
    // 德州竞技场取消报名;
    void TPChallCancelApplyGame( void );
    // 德州竞技场房间信息;
    void TPChallRoomData( void );
    // 德州竞技场请求退出;
    void TPChallRequestQuit( void );
    // 好友私聊;
    void PrivateChat( void );
    // 南京麻将用户选择权限;
    void MahjongUserOperate( int rand_index );
    // 南京麻将出牌;
    void MahjongOutCard( void );
    // 南京麻将用户开始准备;
    void MahjongStartReady( void );
    // 南京麻将用户取消准备;
    void MahjongCancelReady( void );
    // 请求同步道具数据;
    void SynchItemData( void );
    // 使用道具;
    void UseItem( void );
    // 出售道具;
    void SellItem( void );
    // 商城购买道具
    void StoreBuyItem( void );
    // 检验校验码绑定手机号;
    void BindMobileNumberCheck( void );
    // 跑马灯喊话;
    void ChatPaoMaDeng( void );
    // 获取Send Money Limit;
    void GetSendMoneyLimit( void );
    // 搜索PID;
    void SearchPID( void );
    // 同步屏蔽列表;
    void SyncBlackList( void );
    // 移除屏蔽列表;
    void DeleteBlackList( void );
    // 添加屏蔽列表;
    void AddBlackList( void );
    // 请求同步任务数据;
    void SynchMissionData( void );
    // 请求统计积分清零;
    void RestoreScoreData( void );
private:
    // 连接;
    CConnect*       m_Connect;
};

#endif // send_logic_h__