// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_item.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg_item.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PROTOBUF {

namespace {

const ::google::protobuf::Descriptor* PB_Item_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PB_Item_reflection_ = NULL;
const ::google::protobuf::Descriptor* PB_ItemList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PB_ItemList_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_5fitem_2eproto() {
  protobuf_AddDesc_msg_5fitem_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg_item.proto");
  GOOGLE_CHECK(file != NULL);
  PB_Item_descriptor_ = file->message_type(0);
  static const int PB_Item_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_Item, item_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_Item, item_number_),
  };
  PB_Item_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PB_Item_descriptor_,
      PB_Item::default_instance_,
      PB_Item_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_Item, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_Item, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PB_Item));
  PB_ItemList_descriptor_ = file->message_type(1);
  static const int PB_ItemList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_ItemList, item_list_),
  };
  PB_ItemList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PB_ItemList_descriptor_,
      PB_ItemList::default_instance_,
      PB_ItemList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_ItemList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PB_ItemList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PB_ItemList));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_5fitem_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PB_Item_descriptor_, &PB_Item::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PB_ItemList_descriptor_, &PB_ItemList::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msg_5fitem_2eproto() {
  delete PB_Item::default_instance_;
  delete PB_Item_reflection_;
  delete PB_ItemList::default_instance_;
  delete PB_ItemList_reflection_;
}

void protobuf_AddDesc_msg_5fitem_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016msg_item.proto\022\010PROTOBUF\"/\n\007PB_Item\022\017\n"
    "\007item_id\030\001 \001(\r\022\023\n\013item_number\030\002 \001(\r\"3\n\013P"
    "B_ItemList\022$\n\titem_list\030\001 \003(\0132\021.PROTOBUF"
    ".PB_Item", 128);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg_item.proto", &protobuf_RegisterTypes);
  PB_Item::default_instance_ = new PB_Item();
  PB_ItemList::default_instance_ = new PB_ItemList();
  PB_Item::default_instance_->InitAsDefaultInstance();
  PB_ItemList::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_5fitem_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_5fitem_2eproto {
  StaticDescriptorInitializer_msg_5fitem_2eproto() {
    protobuf_AddDesc_msg_5fitem_2eproto();
  }
} static_descriptor_initializer_msg_5fitem_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PB_Item::kItemIdFieldNumber;
const int PB_Item::kItemNumberFieldNumber;
#endif  // !_MSC_VER

PB_Item::PB_Item()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PROTOBUF.PB_Item)
}

void PB_Item::InitAsDefaultInstance() {
}

PB_Item::PB_Item(const PB_Item& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PROTOBUF.PB_Item)
}

void PB_Item::SharedCtor() {
  _cached_size_ = 0;
  item_id_ = 0u;
  item_number_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PB_Item::~PB_Item() {
  // @@protoc_insertion_point(destructor:PROTOBUF.PB_Item)
  SharedDtor();
}

void PB_Item::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PB_Item::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PB_Item::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PB_Item_descriptor_;
}

const PB_Item& PB_Item::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fitem_2eproto();
  return *default_instance_;
}

PB_Item* PB_Item::default_instance_ = NULL;

PB_Item* PB_Item::New() const {
  return new PB_Item;
}

void PB_Item::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<PB_Item*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(item_id_, item_number_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PB_Item::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PROTOBUF.PB_Item)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 item_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &item_id_)));
          set_has_item_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_item_number;
        break;
      }

      // optional uint32 item_number = 2;
      case 2: {
        if (tag == 16) {
         parse_item_number:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &item_number_)));
          set_has_item_number();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PROTOBUF.PB_Item)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PROTOBUF.PB_Item)
  return false;
#undef DO_
}

void PB_Item::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PROTOBUF.PB_Item)
  // optional uint32 item_id = 1;
  if (has_item_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->item_id(), output);
  }

  // optional uint32 item_number = 2;
  if (has_item_number()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->item_number(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PROTOBUF.PB_Item)
}

::google::protobuf::uint8* PB_Item::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PROTOBUF.PB_Item)
  // optional uint32 item_id = 1;
  if (has_item_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->item_id(), target);
  }

  // optional uint32 item_number = 2;
  if (has_item_number()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->item_number(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PROTOBUF.PB_Item)
  return target;
}

int PB_Item::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 item_id = 1;
    if (has_item_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->item_id());
    }

    // optional uint32 item_number = 2;
    if (has_item_number()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->item_number());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PB_Item::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PB_Item* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PB_Item*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PB_Item::MergeFrom(const PB_Item& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_item_id()) {
      set_item_id(from.item_id());
    }
    if (from.has_item_number()) {
      set_item_number(from.item_number());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PB_Item::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PB_Item::CopyFrom(const PB_Item& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PB_Item::IsInitialized() const {

  return true;
}

void PB_Item::Swap(PB_Item* other) {
  if (other != this) {
    std::swap(item_id_, other->item_id_);
    std::swap(item_number_, other->item_number_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PB_Item::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PB_Item_descriptor_;
  metadata.reflection = PB_Item_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PB_ItemList::kItemListFieldNumber;
#endif  // !_MSC_VER

PB_ItemList::PB_ItemList()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PROTOBUF.PB_ItemList)
}

void PB_ItemList::InitAsDefaultInstance() {
}

PB_ItemList::PB_ItemList(const PB_ItemList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PROTOBUF.PB_ItemList)
}

void PB_ItemList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PB_ItemList::~PB_ItemList() {
  // @@protoc_insertion_point(destructor:PROTOBUF.PB_ItemList)
  SharedDtor();
}

void PB_ItemList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PB_ItemList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PB_ItemList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PB_ItemList_descriptor_;
}

const PB_ItemList& PB_ItemList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msg_5fitem_2eproto();
  return *default_instance_;
}

PB_ItemList* PB_ItemList::default_instance_ = NULL;

PB_ItemList* PB_ItemList::New() const {
  return new PB_ItemList;
}

void PB_ItemList::Clear() {
  item_list_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PB_ItemList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PROTOBUF.PB_ItemList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .PROTOBUF.PB_Item item_list = 1;
      case 1: {
        if (tag == 10) {
         parse_item_list:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_item_list()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_item_list;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PROTOBUF.PB_ItemList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PROTOBUF.PB_ItemList)
  return false;
#undef DO_
}

void PB_ItemList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PROTOBUF.PB_ItemList)
  // repeated .PROTOBUF.PB_Item item_list = 1;
  for (int i = 0; i < this->item_list_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->item_list(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PROTOBUF.PB_ItemList)
}

::google::protobuf::uint8* PB_ItemList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PROTOBUF.PB_ItemList)
  // repeated .PROTOBUF.PB_Item item_list = 1;
  for (int i = 0; i < this->item_list_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->item_list(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PROTOBUF.PB_ItemList)
  return target;
}

int PB_ItemList::ByteSize() const {
  int total_size = 0;

  // repeated .PROTOBUF.PB_Item item_list = 1;
  total_size += 1 * this->item_list_size();
  for (int i = 0; i < this->item_list_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->item_list(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PB_ItemList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PB_ItemList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PB_ItemList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PB_ItemList::MergeFrom(const PB_ItemList& from) {
  GOOGLE_CHECK_NE(&from, this);
  item_list_.MergeFrom(from.item_list_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PB_ItemList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PB_ItemList::CopyFrom(const PB_ItemList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PB_ItemList::IsInitialized() const {

  return true;
}

void PB_ItemList::Swap(PB_ItemList* other) {
  if (other != this) {
    item_list_.Swap(&other->item_list_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PB_ItemList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PB_ItemList_descriptor_;
  metadata.reflection = PB_ItemList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PROTOBUF

// @@protoc_insertion_point(global_scope)
