// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_item.proto

#ifndef PROTOBUF_msg_5fitem_2eproto__INCLUDED
#define PROTOBUF_msg_5fitem_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace PROTOBUF {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_5fitem_2eproto();
void protobuf_AssignDesc_msg_5fitem_2eproto();
void protobuf_ShutdownFile_msg_5fitem_2eproto();

class PB_Item;
class PB_ItemList;

// ===================================================================

class PB_Item : public ::google::protobuf::Message {
 public:
  PB_Item();
  virtual ~PB_Item();

  PB_Item(const PB_Item& from);

  inline PB_Item& operator=(const PB_Item& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_Item& default_instance();

  void Swap(PB_Item* other);

  // implements Message ----------------------------------------------

  PB_Item* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_Item& from);
  void MergeFrom(const PB_Item& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 item_id = 1;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 1;
  inline ::google::protobuf::uint32 item_id() const;
  inline void set_item_id(::google::protobuf::uint32 value);

  // optional uint32 item_number = 2;
  inline bool has_item_number() const;
  inline void clear_item_number();
  static const int kItemNumberFieldNumber = 2;
  inline ::google::protobuf::uint32 item_number() const;
  inline void set_item_number(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:PROTOBUF.PB_Item)
 private:
  inline void set_has_item_id();
  inline void clear_has_item_id();
  inline void set_has_item_number();
  inline void clear_has_item_number();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 item_id_;
  ::google::protobuf::uint32 item_number_;
  friend void  protobuf_AddDesc_msg_5fitem_2eproto();
  friend void protobuf_AssignDesc_msg_5fitem_2eproto();
  friend void protobuf_ShutdownFile_msg_5fitem_2eproto();

  void InitAsDefaultInstance();
  static PB_Item* default_instance_;
};
// -------------------------------------------------------------------

class PB_ItemList : public ::google::protobuf::Message {
 public:
  PB_ItemList();
  virtual ~PB_ItemList();

  PB_ItemList(const PB_ItemList& from);

  inline PB_ItemList& operator=(const PB_ItemList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_ItemList& default_instance();

  void Swap(PB_ItemList* other);

  // implements Message ----------------------------------------------

  PB_ItemList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_ItemList& from);
  void MergeFrom(const PB_ItemList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PROTOBUF.PB_Item item_list = 1;
  inline int item_list_size() const;
  inline void clear_item_list();
  static const int kItemListFieldNumber = 1;
  inline const ::PROTOBUF::PB_Item& item_list(int index) const;
  inline ::PROTOBUF::PB_Item* mutable_item_list(int index);
  inline ::PROTOBUF::PB_Item* add_item_list();
  inline const ::google::protobuf::RepeatedPtrField< ::PROTOBUF::PB_Item >&
      item_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::PROTOBUF::PB_Item >*
      mutable_item_list();

  // @@protoc_insertion_point(class_scope:PROTOBUF.PB_ItemList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::PROTOBUF::PB_Item > item_list_;
  friend void  protobuf_AddDesc_msg_5fitem_2eproto();
  friend void protobuf_AssignDesc_msg_5fitem_2eproto();
  friend void protobuf_ShutdownFile_msg_5fitem_2eproto();

  void InitAsDefaultInstance();
  static PB_ItemList* default_instance_;
};
// ===================================================================


// ===================================================================

// PB_Item

// optional uint32 item_id = 1;
inline bool PB_Item::has_item_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_Item::set_has_item_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_Item::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_Item::clear_item_id() {
  item_id_ = 0u;
  clear_has_item_id();
}
inline ::google::protobuf::uint32 PB_Item::item_id() const {
  // @@protoc_insertion_point(field_get:PROTOBUF.PB_Item.item_id)
  return item_id_;
}
inline void PB_Item::set_item_id(::google::protobuf::uint32 value) {
  set_has_item_id();
  item_id_ = value;
  // @@protoc_insertion_point(field_set:PROTOBUF.PB_Item.item_id)
}

// optional uint32 item_number = 2;
inline bool PB_Item::has_item_number() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PB_Item::set_has_item_number() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PB_Item::clear_has_item_number() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PB_Item::clear_item_number() {
  item_number_ = 0u;
  clear_has_item_number();
}
inline ::google::protobuf::uint32 PB_Item::item_number() const {
  // @@protoc_insertion_point(field_get:PROTOBUF.PB_Item.item_number)
  return item_number_;
}
inline void PB_Item::set_item_number(::google::protobuf::uint32 value) {
  set_has_item_number();
  item_number_ = value;
  // @@protoc_insertion_point(field_set:PROTOBUF.PB_Item.item_number)
}

// -------------------------------------------------------------------

// PB_ItemList

// repeated .PROTOBUF.PB_Item item_list = 1;
inline int PB_ItemList::item_list_size() const {
  return item_list_.size();
}
inline void PB_ItemList::clear_item_list() {
  item_list_.Clear();
}
inline const ::PROTOBUF::PB_Item& PB_ItemList::item_list(int index) const {
  // @@protoc_insertion_point(field_get:PROTOBUF.PB_ItemList.item_list)
  return item_list_.Get(index);
}
inline ::PROTOBUF::PB_Item* PB_ItemList::mutable_item_list(int index) {
  // @@protoc_insertion_point(field_mutable:PROTOBUF.PB_ItemList.item_list)
  return item_list_.Mutable(index);
}
inline ::PROTOBUF::PB_Item* PB_ItemList::add_item_list() {
  // @@protoc_insertion_point(field_add:PROTOBUF.PB_ItemList.item_list)
  return item_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PROTOBUF::PB_Item >&
PB_ItemList::item_list() const {
  // @@protoc_insertion_point(field_list:PROTOBUF.PB_ItemList.item_list)
  return item_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::PROTOBUF::PB_Item >*
PB_ItemList::mutable_item_list() {
  // @@protoc_insertion_point(field_mutable_list:PROTOBUF.PB_ItemList.item_list)
  return &item_list_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PROTOBUF

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_5fitem_2eproto__INCLUDED
