// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_error_id.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msg_error_id.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PROTOBUF {

namespace {

const ::google::protobuf::EnumDescriptor* PB_TErrorEnum_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_msg_5ferror_5fid_2eproto() {
  protobuf_AddDesc_msg_5ferror_5fid_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msg_error_id.proto");
  GOOGLE_CHECK(file != NULL);
  PB_TErrorEnum_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msg_5ferror_5fid_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_msg_5ferror_5fid_2eproto() {
}

void protobuf_AddDesc_msg_5ferror_5fid_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022msg_error_id.proto\022\010PROTOBUF*&\n\rPB_TEr"
    "rorEnum\022\025\n\021ERROR_SERVER_FULL\020\000", 70);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msg_error_id.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msg_5ferror_5fid_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msg_5ferror_5fid_2eproto {
  StaticDescriptorInitializer_msg_5ferror_5fid_2eproto() {
    protobuf_AddDesc_msg_5ferror_5fid_2eproto();
  }
} static_descriptor_initializer_msg_5ferror_5fid_2eproto_;
const ::google::protobuf::EnumDescriptor* PB_TErrorEnum_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PB_TErrorEnum_descriptor_;
}
bool PB_TErrorEnum_IsValid(int value) {
  switch(value) {
    case 0:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PROTOBUF

// @@protoc_insertion_point(global_scope)
